# Generated by Django 4.1.7 on 2023-03-01 20:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_pets_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='owners',
            field=models.ManyToManyField(related_name='pets', through='users_pets_api.Owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
