# Generated by Django 4.1.7 on 2023-03-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_pets_api', '0002_alter_pet_owners'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pet',
            constraint=models.CheckConstraint(check=models.Q(('deceased_date__isnull', True), ('deceased_date__gt', models.F('date_of_birth')), _connector='OR'), name='deceased_date_gt_date_of_birth'),
        ),
    ]
