# Generated by Django 4.1.7 on 2023-03-02 01:48

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('users_pets_api', '0003_pet_deceased_date_gt_date_of_birth'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='owner',
            managers=[
                ('owners', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='pet',
            managers=[
                ('pets', django.db.models.manager.Manager()),
            ],
        ),
    ]
