from .admin_provider_router import AdminProviderRouter
from .auth_provider_router import AuthProviderRouter
from .content_types_provider_router import ContentTypesProviderRouter
from .oauth2_dot_provider_router import OAuth2DOTProviderRouter
from .oauth2_dot_restrict_scopes_provider_router import OAuth2DOTRestrictScopesProviderRouter
from .sessions_provider_router import SessionsProviderRouter
